# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: the medium rare programmer
email: me@maloky.com
description: > # this means to ignore newlines until "baseurl:"
  Some rambling about Python, javscript with a bit of agile
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://maloky.com" # the base hostname & protocol for your site
twitter_username: ojorgecosta
github_username:  maloky

# Build settings
markdown: kramdown
